### ISSUE TITLE
Build failure during the pdf export

### ISSUE THREAD

**Issue by lesteve** [lesteve/scikit-learn-tutorial#23]
https://github.com/lesteve/scikit-learn-tutorial/runs/315274429. This has failed for a few days see https://github.com/lesteve/scikit-learn-tutorial/actions. There seems to be a TimeoutError, the PDF export takes 50s and does not complete. Maybe there is a timeout that can be increased with github actions ? ping @brospars.

Full error:
```
Run for f in *.html ; do remarkjs-pdf "$f"; done
Convert file:///home/runner/work/scikit-learn-tutorial/scikit-learn-tutorial/dist/index.html to index.pdf ...
Finished.
Convert file:///home/runner/work/scikit-learn-tutorial/scikit-learn-tutorial/dist/ml_concepts.html to ml_concepts.pdf ...
Finished.
Convert file:///home/runner/work/scikit-learn-tutorial/scikit-learn-tutorial/dist/overfit.html to overfit.pdf ...
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /opt/hostedtoolcache/node/12.13.1/x64/lib/node_modules/remarkjs-pdf/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (/opt/hostedtoolcache/node/12.13.1/x64/lib/node_modules/remarkjs-pdf/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/opt/hostedtoolcache/node/12.13.1/x64/lib/node_modules/remarkjs-pdf/node_modules/puppeteer/lib/Page.js:675:49)
    at Page.<anonymous> (/opt/hostedtoolcache/node/12.13.1/x64/lib/node_modules/remarkjs-pdf/node_modules/puppeteer/lib/helper.js:112:23)
    at convertPdf (/opt/hostedtoolcache/node/12.13.1/x64/lib/node_modules/remarkjs-pdf/remarkjs-pdf.js:80:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/opt/hostedtoolcache/node/12.13.1/x64/lib/node_modules/remarkjs-pdf/remarkjs-pdf.js:69:5) {
  name: 'TimeoutError'
}
##[error]Process completed with exit code 10.
```

**Comment by glemaitre** [comment]
They are the slides isn't it?

**Comment by lesteve** [comment]
Yep

**Comment by brospars** [comment]
The overfit.html contains a lot of images (base64 encoded) however remarkjs-pdf use an headless chrome that times out after 30s. I've just made a [PR](https://github.com/bellbind/remarkjs-pdf/pull/2) to address that issue.

**Comment by lesteve** [comment]
Moved to https://github.com/INRIA/scikit-learn-mooc/issues/1.
